# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostname=localhost

GET http://{{hostname}}:5177/ HTTP/1.1

###

GET http://{{hostname}}:5177/games HTTP/1.1

###

GET http://{{hostname}}:5177/games/1 HTTP/1.1

###

POST http://{{hostname}}:5177/games HTTP/1.1
Content-Type: application/json

{
  "name": "Test2",
  "genre": "TestGenre",
  "price": 1199.99,
  "releaseDate": "1980-12-31"
}

###

PUT http://{{hostname}}:5177/games/1 HTTP/1.1
Content-Type: application/json

{
  "name": "TestReplace",
  "genre": "TestGenreReplace",
  "price": 199.99,
  "releaseDate": "1977-12-31"
}

###

DELETE http://{{hostname}}:5177/games/1 HTTP/1.1
